name: Generate XCFramework

on:
  workflow_run:
    workflows: ["Build Dependencies"]
    types:
      - completed
  workflow_dispatch:

jobs:
  xcframework:
    name: Generate XCFramework
    runs-on: macos-26
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate XCFramework
        uses: ./.github/actions/generate-xcframework-cross-workflow
        with:
          workflow-run-id: ${{ github.event.workflow_run.id }}
